### ISSUE TITLE
Feature Request - Environment variable for defaulting to dark theme

### ISSUE THREAD

**Issue by librick** [amerkurev/doku#30]
Hey, great project! I'm working on setting up a media server using docker containers, and Doku is a great way for me to keep an eye on disk usage. My goal for my project is to allow anyone to spin up a media server with really good defaults.

I think it would be beneficial to have an environment variable/configuration option to control the default theme for Doku. I prefer the dark theme, but Doku currently defaults to the light theme. It'd be great if I could modify the environment of my `docker-compose.yml` file to tell Doku to start with the dark theme by default (i.e., with no user action).

Something like `DOKU_THEME=<light|dark>`.
Then my `docker-compose.yml` file could look like:
```
  doku:
    image: amerkurev/doku:v0.0.16
    ports:
      - 9090:9090
    environment:
        DOKU_THEME=dark
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/hostroot:ro
```
This pattern of declarative configuration using environment variables with the `DOKU_` prefix is really powerful and I think would be useful for anyone who wants to run Doku in containers.

This is a really great project, thanks for contributing to open source!
