### ISSUE TITLE
Unable to set log level using docker-compose

### ISSUE THREAD

**Issue by bedelaitre** [amerkurev/doku#32]
I'm trying to set the log level to "debug" in portainer, but can't find how to do it. I've no debug traces.

Here is my docker compose file content:

```
version: "3.9"
services:
  doku:
    container_name: Doku
    image: amerkurev/doku:latest
    mem_limit: 4g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    restart: on-failure:5
    ports:
      - 9090:9090
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/hostroot:ro
    environment:
      LEVEL: debug
```
