### ISSUE TITLE
Container section shows blank page due to RepoTags error

### ISSUE THREAD

**Issue by Else00** [amerkurev/doku#37]
# Container section shows blank page due to RepoTags error

## Description
The containers section (`/containers`) shows a blank page due to a JavaScript error. The error occurs when trying to access `RepoTags` property on containers that might not have it.

## Error Details
Console shows the following error:
```js
TypeError: null is not an object (evaluating 'r.RepoTags.join')
```

This error likely occurs when:
- Containers are created from images without tags (dangling images)
- Containers whose source images have been removed

## Steps to Reproduce
1. Create docker-compose.yml:
```yaml
version: "3"
services:
  docu:
    image: amerkurev/doku:v0.0.16
    ports:
      - 9090:9090
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/hostroot:ro
```
2. Run `docker-compose up -d`
3. Navigate to `/containers` section
4. Page remains blank with JS console errors

## Expected Behavior
- The containers section should display correctly even when containers have no RepoTags
- Should handle null/undefined RepoTags gracefully

## Environment
- Doku version: v0.0.16 (via docker-compose)
- Browser: tried with `Chromium 132.0.6834.110`, `Safari 18.3 (20620.2.4.11.5)`, `Firefox 135.0`
- OS: `macOS 15.3 (24D60)`
